source ~/.profile || true
test -s ~/.profile.local && . ~/.profile.local || true

PS1="\$(/usr/bin/prettyprompt \$?)"
export PRETTYPROMPT_SHELL="bash"

if [ -d $HOME/.rbenv ]; then
	eval "$(rbenv init -)"
fi
