# Sample .bashrc for SuSE Linux
# Copyright (c) SuSE GmbH Nuernberg

# There are 3 different types of shells in bash: the login shell, normal shell
# and interactive shell. Login shells read ~/.profile and interactive shells
# read ~/.bashrc; in our setup, /etc/profile sources ~/.bashrc - thus all
# settings made here will also take effect in a login shell.

test -s ~/.alias && . ~/.alias || true
test -z "$LOCALPROFILEREAD" && source ~/.profile || true
if [[ -n $PS1 ]]; then
	PS1="\$($HOME/bin/prettyprompt)"
	export PRETTYPROMPT_SHELL="bash"
fi
