[[block]]
block = "backlight"
step_width = 2 # percent
minimum = 1    # percent

[[block]]
block = "battery"
interval = 2
format = " $icon $percentage $power "
full_format = " $icon $percentage $power "
empty_format = " $icon $percentage $power "
not_charging_format = " $icon $percentage $power "
