[[block]]
block = "backlight"
step_width = 2 # percent
minimum = 1    # percent

[[block]]
block = "battery"
interval = 2
format = " $icon $percentage {$power| 0W} "
full_format = " $icon $percentage {$power| 0W} "
empty_format = " $icon $percentage {$power| 0W} "
not_charging_format = " $icon $percentage {$power| 0W} "
