icons_format = "{icon}"

[icons]
name = "none"
[icons.overrides]
bat_full = " bat "
bat_charging = " pwr "
bat_discharging = " bat "
bat_not_available = " bat "
bat_10 = " bat "
bat_20 = " bat "
bat_30 = " bat "
bat_40 = " bat "
bat_50 = " bat "
bat_60 = " bat "
bat_70 = " bat "
bat_80 = " bat "
bat_90 = " bat "
backlight_empty = " bl "
backlight_1 = " bl "
backlight_2 = " bl "
backlight_3 = " bl "
backlight_4 = " bl "
backlight_5 = " bl "
backlight_6 = " bl "
backlight_7 = " bl "
backlight_8 = " bl "
backlight_9 = " bl "
backlight_10 = " bl "
backlight_11 = " bl "
backlight_12 = " bl "
backlight_13 = " bl "
backlight_full = " bl "
cpu = " cpu "
memory_mem = " mem "
net_wired = " en "
net_wireless = " wl "
volume_muted = " vol × "
volume_full = " vol "
volume_half = " vol "
volume_empty = " vol "
music_prev = "  << "
music_next = " >>  "
music_play = " ++ "
music_pause = " -- "
music = " "
time = " "

[theme]
name = "gruvbox-dark"
[theme.overrides]
alternating_tint_bg = "#141414"
separator = ""
