[[block]]
block = "cpu"
format = "{utilization:02}"
interval = 1

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents:02}"
format_swap = "{swap_used_percents:02}"
clickable = false

[[block]]
block = "sound"
driver = "pulseaudio"
