[[block]]
block = "cpu"
format = " cpu $utilization.eng(w:2,pad_with:0) "
interval = 1

[[block]]
block = "memory"
format = " mem $mem_used_percents.eng(w:2,pad_with:0) "

[[block]]
block = "sound"
driver = "pulseaudio"
format = " vol {$volume|×} "
